title: "joebew42.github.io"
email: ""
description: ""
baseurl: ""
url: "http://joebew42.github.io"
twitter_username: joebew42
github_username:  joebew42

markdown: kramdown
exclude: ['notes']
gems:
  - jekyll-youtube