title: "Joe Bew"
title_image: "/assets/title-image.jpg"
email: ""
description: ""
baseurl: ""
permalink: pretty
url: "https://joebew42.github.io"
twitter_username: joebew42
github_username:  joebew42

excerpt_separator: <!--more-->

markdown: kramdown
exclude: ['notes']

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "tag"

plugins:
  - jemoji
