title: "Joe Bew"
email: ""
description: ""
baseurl: ""
permalink: pretty
url: "http://joebew42.github.io"
twitter_username: joebew42
github_username:  joebew42

excerpt_separator: <!--more-->

markdown: kramdown
exclude: ['notes']

plugins:
  - jemoji
