title: "joebew42.github.io"
email: ""
description: ""
baseurl: ""
url: "http://joebew42.github.io"
twitter_username: joebew42
github_username:  joebew42

excerpt_separator: <!--more-->

markdown: kramdown
exclude: ['notes']
